# Generated by Django 4.2.4 on 2023-08-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="record",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="record",
            name="email",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="record",
            name="pincode",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="record",
            name="state",
            field=models.CharField(max_length=50),
        ),
    ]
