# Generated by Django 4.2.4 on 2023-09-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_alter_record_address_alter_record_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="record",
            name="pincode",
            field=models.IntegerField(max_length=20),
        ),
    ]
