# Generated by Django 4.2.4 on 2023-10-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_lead_customerquery"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerquery",
            name="query",
            field=models.CharField(
                choices=[
                    ("Product Inquiries", "Product Inquiries"),
                    ("Order Status and Tracking", "Order Status and Tracking"),
                    ("Complaints", "Complaints"),
                    ("Returns and Refunds", "Returns and Refunds"),
                    ("Payment Issues", "Payment Issues"),
                    ("Account Management", "Account Management"),
                    ("Technical Support", "Technical Support"),
                    ("Offers and Promotions", "Offers and Promotions"),
                    ("Shipping and Delivery Issues", "Shipping and Delivery Issues"),
                    ("Feedback and Suggestions", "Feedback and Suggestions"),
                    ("General Inquiries", "General Inquiries"),
                ],
                default="General Inquiries",
                max_length=50,
            ),
        ),
    ]
