# Generated by Django 4.2.4 on 2023-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0008_alter_lead_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerquery",
            name="query",
            field=models.CharField(
                choices=[
                    ("Product Inquiries", "Product Inquiries"),
                    ("Order Status and Tracking", "Order Status and Tracking"),
                    ("Complaints", "Complaints"),
                    ("Returns and Refunds", "Returns and Refunds"),
                    ("Payment Issues", "Payment Issues"),
                    ("Account Management", "Account Management"),
                    ("Technical Support", "Technical Support"),
                    ("Offers and Promotions", "Offers and Promotions"),
                    ("Feedback and Suggestions", "Feedback and Suggestions"),
                    ("General Inquiries", "General Inquiries"),
                ],
                default="General Inquiries",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="designation",
            field=models.CharField(
                choices=[
                    (
                        "Customer Support Representative",
                        "Customer Support Representative",
                    ),
                    ("Product Specialist", "Product Specialist"),
                    ("Marketing Coordinator", "Marketing Coordinator"),
                    ("IT Support Technician", "IT Support Technician"),
                    ("Financial Analyst", "Financial Analyst"),
                    ("Logistics Coordinator", "Logistics Coordinator"),
                    ("Lead", "Lead"),
                ],
                max_length=50,
            ),
        ),
    ]
