# Generated by Django 4.2.4 on 2023-10-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0009_alter_customerquery_query_alter_lead_designation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lead",
            new_name="Employee",
        ),
        migrations.RenameField(
            model_name="customerquery",
            old_name="lead_assigned",
            new_name="employee_assigned",
        ),
    ]
